// /data/data/com.termux/files/home/projects/src/auto-imports.d.ts
// Generated by unplugin-auto-import
// Do not edit manually

declare global {
  namespace AutoImport {
    interface Imports {
      // React
      useState: typeof import('react').useState
      useEffect: typeof import('react').useEffect
      useContext: typeof import('react').useContext
      useRef: typeof import('react').useRef
      useMemo: typeof import('react').useMemo
      useCallback: typeof import('react').useCallback
      useReducer: typeof import('react').useReducer
      useLayoutEffect: typeof import('react').useLayoutEffect
      useImperativeHandle: typeof import('react').useImperativeHandle
      useDebugValue: typeof import('react').useDebugValue
      ReactNode: typeof import('react').ReactNode
      ReactElement: typeof import('react').ReactElement

      // React Router DOM
      useNavigate: typeof import('react-router-dom').useNavigate
      useParams: typeof import('react-router-dom').useParams
      useLocation: typeof import('react-router-dom').useLocation
      Link: typeof import('react-router-dom').Link
      NavLink: typeof import('react-router-dom').NavLink
    }
  }
}

export {}
