# pnpm-workspace.yaml - กำหนด workspace สำหรับโปรเจกต์แบบ Monorepo
# ระบุโฟลเดอร์ที่เก็บ packages ย่อยทั้งหมด
packages:
  - 'packages/*' # โฟลเดอร์ packages ที่เก็บแพ็กเกจย่อย
  - 'libs/*' # โฟลเดอร์ libs สำหรับเก็บไลบรารีร่วม
  - 'apps/*' # โฟลเดอร์ apps สำหรับเก็บแอปพลิเคชันย่อย
  - '.' # โฟลเดอร์ root ที่มี package.json ของโปรเจกต์หลัก
