import { precacheAndRoute } from 'workbox-precaching'
import { registerRoute } from 'workbox-routing'
import { StaleWhileRevalidate } from 'workbox-strategies'

// Precache all assets generated by the build process
precacheAndRoute(self.__WB_MANIFEST || [])

// Cache images with stale-while-revalidate strategy
registerRoute(
  ({ request }) => request.destination === 'image',
  new StaleWhileRevalidate({
    cacheName: 'images-cache',
  })
)

// Activate service worker immediately after installation
self.addEventListener('install', event => {
  self.skipWaiting()
})

// Take control of uncontrolled clients as soon as the service worker activates
self.addEventListener('activate', event => {
  self.clients.claim()
})
